package com.mybatis.cn.entity;

/**
 * Created by liKun on 2018/1/11 0011.
 */
public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.ID
     *
     * @mbggenerated Tue Jan 09 16:14:52 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.NAME
     *
     * @mbggenerated Tue Jan 09 16:14:52 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.ID_NUM
     *
     * @mbggenerated Tue Jan 09 16:14:52 CST 2018
     */
    private String identity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.PWD
     *
     * @mbggenerated Tue Jan 09 16:14:52 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USER.PHONE_NUM
     *
     * @mbggenerated Tue Jan 09 16:14:52 CST 2018
     */
    private String phone;

    public User() {
    }

    public User(String id, String name, String identity, String password, String phone) {
        this.id = id;
        this.name = name;
        this.identity = identity;
        this.password = password;
        this.phone = phone;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getIdentity() {
        return identity;
    }

    public void setIdentity(String identity) {
        this.identity = identity;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }
}
